gas_adjustment = 1

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[[deviation_thresholds]]
base = "USDT"
threshold = "1.5"

[[deviation_thresholds]]
base = "UMEE"
threshold = "1.5"

[[deviation_thresholds]]
base = "ATOM"
threshold = "1.5"

[[deviation_thresholds]]
base = "USDC"
threshold = "1.5"

[[deviation_thresholds]]
base = "CRO"
threshold = "1.5"

[[deviation_thresholds]]
base = "DAI"
threshold = "2"

[[deviation_thresholds]]
base = "ETH"
threshold = "2"

[[deviation_thresholds]]
base = "WBTC"
threshold = "1.5"

[[currency_pairs]]
base = "UMEE"
providers = [
  "okx",
  "gate",
  "mexc",
]
quote = "USDT"

[[currency_pairs]]
base = "USDT"
providers = [
  "kraken",
  "coinbase",
  "binanceus",
]
quote = "USD"

[[currency_pairs]]
base = "ATOM"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ATOM"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "USDC"
providers = [
  "okx",
  "bitget",
  "kraken",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "okx",
  "bitget",
  "huobi",
]
quote = "USDT"

[[currency_pairs]]
base = "DAI"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "ETH"
providers = [
  "okx",
  "bitget",
]
quote = "USDT"

[[currency_pairs]]
base = "ETH"
providers = [
  "kraken",
]
quote = "USD"

[[currency_pairs]]
base = "WBTC"
providers = [
  "okx",
  "bitget",
  "crypto",
]
quote = "USDT"


[account]
address = "umee1nuh3h59fsj8hvgqr778q7knjag3qtaq2h6v2cp"
chain_id = "umee-1"
validator = "umeevaloper1mkv4myppz2w0d3nr2dh9fv5kcwaaqnzfvnm6qf"

[keyring]
backend = "os"
dir = "/root/.umee"
pass = ""

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "umee-1"]]
service-name = "price-feeder"
prometheus-retention-time = 100

[[provider_endpoints]]
name = "binance"
rest = "https://api1.binance.com"
websocket = "stream.binance.com:9443"
